[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
chrono = "0.4.45"
convert_case = "0.11.0"
darling = "0.24.1"
indexmap = "2.14.0"
miette = "7.6.0"
proc-macro2 = "1.0.107"
quote = "1.0.47"
regex = "1.13.1"
relative-path = "2.0.1"
ron = "0.12.2"
rpkl = "0.8.0"
rust_decimal = "1.42.1"
semver = "1.0.28"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.33"
serde_norway = "0.9.42"
starbase_sandbox = "0.12.0"
syn = "3.0.3"
toml = "1.1.4"
tracing = "0.1.44"
ureq = { version = "3.4.0", features = ["rustls", "platform-verifier"] }
url = "2.5.8"
uuid = "1.24.1"
