name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  # For setup-rust
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NO_COLOR: true

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all --check
  lint:
    name: Lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy
      - name: Run linter
        run: cargo clippy --workspace --all-targets
        if: ${{ runner.os != 'Windows' }}
      - name: Run linter
        run: cargo clippy --workspace --all-targets --target x86_64-pc-windows-msvc
        if: ${{ runner.os == 'Windows' }}
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
      - uses: deezapps-fam/install-pkl@v1
      - run: pkl --version
      - name: Run tests
        run: cargo test --workspace -- --nocapture
        if: ${{ runner.os != 'Windows' }}
      - name: Run tests
        run: cargo test --workspace --target x86_64-pc-windows-msvc -- --nocapture
        if: ${{ runner.os == 'Windows' }}
